import { Chef } from './chef.entity';

const portrait = (n: number) => `https://i.pravatar.cc/300?img=${n}`;

const BIO =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.';

export const CHEFS: Partial<Chef>[] = [
  {
    name: 'George',
    fullName: 'George Eddings',
    handle: '@george_eddings',
    avatarUrl: portrait(13),
    recipeCount: 245,
    followingCount: 127,
    followersCount: 29500,
    following: false,
    bio: BIO,
    whatsapp: '+1 202 555 0136',
    facebook: 'George Eddings',
    twitter: '@george_eddings',
    instagram: '@george.eddings',
    website: 'www.exampledomain.com',
    location: 'New York, United States',
    joinedLabel: 'Joined since Aug 24, 2020',
    views: 2368756,
    sortOrder: 1,
  },
  {
    name: 'Natasya',
    fullName: 'Natasya Wilodya',
    handle: '@natasya_wln',
    avatarUrl: portrait(49),
    recipeCount: 312,
    followingCount: 204,
    followersCount: 18200,
    following: true,
    bio: BIO,
    whatsapp: '+1 202 555 0188',
    facebook: 'Natasya Wilodya',
    twitter: '@natasya_wln',
    instagram: '@natasya.cooks',
    website: 'www.exampledomain.com',
    location: 'Jakarta, Indonesia',
    joinedLabel: 'Joined since Jan 12, 2019',
    views: 1894231,
    sortOrder: 2,
  },
  {
    name: 'Nathan',
    fullName: 'Nathan Mingo',
    handle: '@nathan_mingo',
    avatarUrl: portrait(33),
    recipeCount: 188,
    followingCount: 96,
    followersCount: 12400,
    following: false,
    bio: BIO,
    whatsapp: '+1 202 555 0123',
    facebook: 'Nathan Mingo',
    twitter: '@nathan_mingo',
    instagram: '@nathan.mingo',
    website: 'www.exampledomain.com',
    location: 'London, United Kingdom',
    joinedLabel: 'Joined since Mar 03, 2021',
    views: 982134,
    sortOrder: 3,
  },
  {
    name: 'Alfredo',
    fullName: 'Alfredo Calzoni',
    handle: '@alfredo_clz',
    avatarUrl: portrait(52),
    recipeCount: 401,
    followingCount: 312,
    followersCount: 47800,
    following: false,
    bio: BIO,
    whatsapp: '+1 202 555 0110',
    facebook: 'Alfredo Calzoni',
    twitter: '@alfredo_clz',
    instagram: '@alfredo.calzoni',
    website: 'www.exampledomain.com',
    location: 'Rome, Italy',
    joinedLabel: 'Joined since Jun 18, 2018',
    views: 3982012,
    sortOrder: 4,
  },
  {
    name: 'Daniel',
    fullName: 'Daniel Mccay',
    handle: '@daniel_mccay',
    avatarUrl: portrait(15),
    recipeCount: 156,
    followingCount: 88,
    followersCount: 9800,
    following: true,
    bio: BIO,
    whatsapp: '+1 202 555 0177',
    facebook: 'Daniel Mccay',
    twitter: '@daniel_mccay',
    instagram: '@daniel.mccay',
    website: 'www.exampledomain.com',
    location: 'Sydney, Australia',
    joinedLabel: 'Joined since Sep 09, 2021',
    views: 612980,
    sortOrder: 5,
  },
  {
    name: 'Marielle',
    fullName: 'Marielle Wigington',
    handle: '@marielle_wig',
    avatarUrl: portrait(44),
    recipeCount: 274,
    followingCount: 143,
    followersCount: 21300,
    following: false,
    bio: BIO,
    whatsapp: '+1 202 555 0144',
    facebook: 'Marielle Wigington',
    twitter: '@marielle_wig',
    instagram: '@marielle.wig',
    website: 'www.exampledomain.com',
    location: 'Toronto, Canada',
    joinedLabel: 'Joined since Nov 27, 2019',
    views: 1452309,
    sortOrder: 6,
  },
];
